### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by bart** [rigor789/nativescript-tailwind#1]
Hey @rigor789, how must I use this repository? Should I clone it and do npm install or is it a nativescript plugin? How can I use it in combination with vue.js? My favourite setup would be Nativescript + Vue.js + Tailwindcss.

Thanks a lot for all the effort you put into the nativescript vue project!

**Comment by bart** [comment]
I'm sure it's a template, right? How can I combine it with the vue.js template?

**Comment by rigor789** [comment]
@bart if you only want to use the default config, you can import the css from `nativescript-tailwind/dist/tailwind.css`. If you need to make changes to the config, you should clone it and tweak the config, and build the css file with `npm run build` and use the css file from the `dist` folder. I plan to make this easier, so you can just drop it in an app and it will work, just haven't had time to work on it.

**Comment by bart** [comment]
Awesome @rigor789 thanks a lot. I'll try it out and maybe I can start working on it creating a vue with tailwind nativescript template.

**Comment by rigor789** [comment]
I usually add `<style src="nativescript-tailwind/dist/tailwind.css"/>` to my `App.vue` and use it right away :)

**Comment by shilik** [comment]
Hi, @rigor789 

Any  update for the details of using nativescript-tailwind and nativescript-vue after installing it with `npm i --save nativescript-tailwaind`
I followed the discussion, installing it with command npm above, then added `<style src="nativescript-tailwind/dist/tailwind.css"/>` in my app.vue, but unfortunately got my app crashed during the launching phase.
