### ISSUE TITLE
Valid NativeScript plugin?

### ISSUE THREAD

**Issue by warksit** [rigor789/nativescript-tailwind#2]
After running:
`tns plugin add nativescript-tailwind`
as per [https://market.nativescript.org/plugins/nativescript-tailwind](https://market.nativescript.org/plugins/nativescript-tailwind)
I get the following error:
`nativescript-tailwind is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.`

What I am doing wrong?

**Comment by rigor789** [comment]
Try with `npm i --save nativescript-tailwind` instead. I haven't had the chance to work on this for a while (it should work just fine, but I have/had plans to add support for tailwind.js configs and such).

**Comment by salvationarinze** [comment]
Hi. Please have you made this tailwind.js config support available?

**Comment by rigor789** [comment]
Yes - see readme for multiple ways to provide your own config. In my projects I use the 3rd option via postcss, and I have a tailwind.config.js in my app.

This has also been fixed by specifying the nativescript key in package.json so `tns add` should work now as well!
