### ISSUE TITLE
background color property is not working on android 

### ISSUE THREAD

**Issue by shilik** [rigor789/nativescript-tailwind#26]
Hi @rigor789 

Thanks for the great plugin. 
It has been must-have part of my development of apps.
I have no problems with it on iOS platform until when I checked it on my Pixel2.
All properties related with bg-xxx-xxx all turned either black or white.
I have followed your instruction in the readme and tried several times but in vain.
Is this a bug?

![Screenshot_20200714-101058](https://user-images.githubusercontent.com/1404868/87372630-a3263300-c5ba-11ea-8043-097274ffba17.png)

**Comment by shilik** [comment]
I found out that this happens only when dark-mode is on. Any suggestion?

**Comment by rigor789** [comment]
@shilik I've always been disabling dark mode, because of the way it changes colors. I'm not 100% if that's the system default, or NS doing something funky, but disabling it is the most reliable way to ensure your colors show up as you intended.

**Comment by shilik** [comment]
> @shilik I've always been disabling dark mode, because of the way it changes colors. I'm not 100% if that's the system default, or NS doing something funky, but disabling it is the most reliable way to ensure your colors show up as you intended.

I see. Thanks for the suggestion.
