### ISSUE TITLE
how to use @apply directive?

### ISSUE THREAD

**Issue by shilik** [rigor789/nativescript-tailwind#3]
hi, @rigor789 

Thanks for this great plugin.
I've tried this plugin in my project, and it seems to work great so far.
To make the layout more concise, I want to put it in the style section like the following. It is said that it is required to add @apply directive in the style section. but unfortunately this doesn't work for nativescript-vue project.
Is there any way to get this problem solved? 
```
<style>
  .btn {
    @apply font-bold py-2 px-4 rounded;
  }
  .btn-blue {
    @apply bg-blue text-white;
  }
  .btn-blue:hover {
    @apply bg-blue-dark;
  }
</style> 
```

**Comment by rigor789** [comment]
Currently not easily, since this is just a build of the tailwind's default config. Ideally you'll be able to provide your own config, and your own css with `@apply` in the next release. I don't currently have time to implement this, so your best bet would be to fork the repo, tweak config / css and build the css file which you can copy over to your app.

**Comment by shilik** [comment]
@rigor789 
Thank you very much for the suggestion.
I have enjoyed using it in my new project even though the @apply directive is not available yet. :)
Your contribution and efforts has made my life of developing apps easier. 👍 
Thanks again.

Best

**Comment by rigor789** [comment]
@shilik i have released an update which adds support for using it as you would in any webapp via webpack. I have yet to document this, but if you can setup postcss then follow tailwind official guide and add `nativescript-tailwind` as a postcss plugin after tailwind.

**Comment by shilik** [comment]
@rigor789 

Thank you very much for the information. I will give it a try.
:)
Best regards,

Shilik

**Comment by rigor789** [comment]
Updated docs - not too detailed, but I believe it should get everyone started!
