### ISSUE TITLE
tailwindcss version upgrade

### ISSUE THREAD

**Issue by joshua1** [rigor789/nativescript-tailwind#41]
Hi @rigor789  , Any plan to upgrade Tailwindcss and Postcss versions. There is a chance of more supported properties with the latest version of TailwindCSS for example

**Comment by rigor789** [comment]
Opened #64 - has a built version with latest tailwind, but some issues too, listed in the pr.

**Comment by joshua1** [comment]
Hi @rigor789 is there any update on this . I see the Pr is still pending. Thanks

**Comment by rigor789** [comment]
I guess the last issue is gradient support - which could be fixed/tracked separately. Will try to get this merged over the weekend!

**Comment by rigor789** [comment]
Update: that weekend has passed, sorry - but just discovered an issue that affects the release: https://github.com/rigor789/nativescript-tailwind/pull/64#issuecomment-777391618

**Comment by rigor789** [comment]
Releasesd 2.0.0
