### ISSUE TITLE
postcss-nativescript was deprecated

### ISSUE THREAD

**Issue by QuentinMichinot** [rigor789/nativescript-tailwind#78]
Hello there :)

thanks for this plugin Tailwind !

"postcss-nativescript": "0.0.0",
"postcss": "^8.2.8",

When I try to use the tailwind config with this commande
`npx nativescript-tailwind tailwind.config.js`

He told me
`postcss-nativescript: postcss.plugin was deprecated.` for migrate postcss-8

thanks for your help !

oups (I think is that : https://github.com/postcss/postcss/issues/1526)

**Comment by rigor789** [comment]
Yep, already in progress here: https://github.com/rigor789/nativescript-tailwind/pull/64 and somewhat blocked by that issue https://github.com/postcss/postcss/issues/1526

**Comment by rigor789** [comment]
Published 2.0.0 - we're pinning the version of postcss, though would need to eventually get that fixed.
